/*
 * Created on 2019-11-08 ( Date ISO 2019-11-08 - Time 11:11:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.web.rest.commons;

import java.util.logging.Level;

/**
 * The logger level <br>
 * 
 * @author Telosys
 *
 */
public class LoggerLevel {

	// Set the logger level here :
	
	//public final static Level LEVEL = Level.OFF ;
	public final static Level LEVEL = Level.ALL ;
	
}
